media_album:
    resource: "@MediaBundle/Resources/config/routing/album.yml"
    prefix:   /

media_commentaire:
        resource: "@MediaBundle/Resources/config/routing/commentaire.yml"
        prefix:   /commentaire

media_homepage:
    path:     /home
    defaults: { _controller: MediaBundle:Default:index }
